services:
  web-joyeria:
    build: .
    container_name: web-joyeria
    ports:
      - "8000:80"
    volumes:
      - ./template:/var/www/html
    depends_on:
      - mysql-joyeria

  mysql-joyeria:
    image: mysql:8.0
    container_name: mysql-joyeria
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: joyeria
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin-joyeria:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-joyeria
    environment:
      PMA_HOST: mysql-joyeria
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql-joyeria

volumes:
  db_data:
